### PR TITLE
Fix area title position

### LINKED ISSUE #49: Improve Areas on Home view
What an amazing dashboard strategy you have created. Thanks! 👏 Great work and finally I can get rid of Dwains Dashboard (it was great for a while, but has been very buggy lately for me).

Two things:
1.  I'd like to be able to configure the title for "Areas" in the Home view (much like I can set the title for domains)
2. "Areas" title looks misplaced to me. It is in the left column, while all areas are in the right column. Please see screenshot:
image

### PR DESCRIPTION
**Pull request by AalianKhan**
Put the area title card inside the vertical stack so everything matches up in the desktop view. Fixes  #49

### CODE REVIEW

**Comment by AalianKhan** [comment]
After this fix, should we create a new release?

File: src/views/HomeView.js [hunk 1]
```diff
@@ -182,6 +178,11 @@ class HomeView extends AbstractView {
    */
   #createAreaCards() {
     const groupedCards = [];
+    groupedCards.push({
```
Comment (DigiLive) [inline src/views/HomeView.js]: `groupedCards` can be initialized as a single element array with this object instead of initializing an empty array ans pushing immediately.

```js
    const groupedCards = [{
      type: "custom:mushroom-title-card",
      title: "Areas",
    }];
```

**Review by DigiLive — CHANGES_REQUESTED** [review]

**Comment by DigiLive** [comment]
> After this fix, should we create a new release?

Actually I'm not sure.
Until now, I've created pre-releases only since a full release will contain breaking changes for the users which aren't on the beta channel.

Also, There's still issue #26 which i.m.o. should have the highest priority.
Currently it's assigned to me, but I have little time momentarily to resolve it.
Maybe you can help to pinpoint the issue in the code?

If you're comfortable with above (and I assume there aren't any other know bugs), you could create a 1.0.0 normal-release.
You should clearly point out the regular AND breaking changes in the description of the release since those are presented in HACS. This would be a merge of the latest changes and the changes described at the alpha.1 and alpha.2 releases.

**Review by DigiLive — APPROVED** [review]

**Comment by AalianKhan** [comment]
I see, 
My main issue is that the readme shown is not the correct one and I get lots of messages because of that. I think it is time to release 1.0.0 
I am a bit biased here considering that bug doesn't affect me
